//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModelsXML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewModelsXML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;!--Main List of Radio Stations XML--&gt;
        ///&lt;stations&gt;
        ///  &lt;station id=&quot;10&quot;&gt;
        ///    &lt;url&gt;http://uplink.intronic.nl/rgrfm_oldiesradio&lt;/url&gt;
        ///    &lt;name&gt;Oldiesradio RGR&lt;/name&gt;
        ///    &lt;category&gt;Oldies&lt;/category&gt;
        ///    &lt;country&gt;&lt;/country&gt;
        ///  &lt;/station&gt;
        ///  &lt;station id=&quot;11&quot;&gt;
        ///    &lt;url&gt;http://199.58.160.146:8006/&lt;/url&gt;
        ///    &lt;name&gt;Psychedelicized Radio&lt;/name&gt;
        ///    &lt;category&gt;Psychedelic&lt;/category&gt;
        ///    &lt;country&gt;&lt;/country&gt;
        ///  &lt;/station&gt;
        ///  &lt;station id=&quot;12&quot;&gt;
        ///    &lt;url&gt;http [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RadioStations {
            get {
                return ResourceManager.GetString("RadioStations", resourceCulture);
            }
        }
    }
}
